- name: nginx install and run
  hosts: web
  become: yes #take sudo access
  tasks:
  - name: install nginx
    ansible.builtin.package: #heterongenous module that can be work for all distributions
      name: nginx
      state: present #present= installed, absent= uninstalled