- name: command vs shell
  hosts: local
  connection: local
  tasks:
    - name: execute the command
      ansible.builtin.shell: ls -ltr > /tmp/output.txt # logs in to the server and executes the command
      # command module, just issues the command 

    - name: check the process
      ansible.builtin.shell: ps -ef | grep ssh
      register: output

    - name: check the process
      ansible.builtin.command: ps -ef | grep ssh
      register: output