- name: create ec2 instance and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-0351597a4ca706e37" #replace with your subnet_id
    sg_id: "sg-094106cbffaf0c40b"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: srinivas.fun
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: create r53 records
    ansible.builtin.route53:
      state: present
      zone: "{{ zone }}" 
      record: "{{ item.item }}.{{ zone }}" #ex->(mysql).(srinivas.fun)->(item.item).(zone)
      type: A
      ttl: 1
      value: "{{ item.instance[0].private_ip_address }}"
      wait: true
      overwrite: true # overrides existing records
