- name: create ec2 instance and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-0351597a4ca706e37"
    sg_id: "sg-094106cbffaf0c40b"
    ami_id: "ami-09c813fb71547fc4f"
  instances:
  - mysql
  - backend
  - frontend
  tasks:
  - name: start an instance with a pubilc IP address
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      loop: "{{ instances }}"
      register: ec2-instances
      